# Site settings
title: Simple Joy Yoga
email: simplejoyyoga@gmail.com
url: https://gsimplejoyyoga.com
description: "Simple Joy Yoga is yoga for all ages. Students learn the power of healthy breathing & the joy of being playfully present in the body. Each class we link breath and movement as we connect body, mind, & heart. You are invited to experience the centering practice of Simple Joy Yoga."
keywords: "Yoga, Simple, Joy, Chair Yoga, Gentle"
# skills: "Web Developer - Graphic Artist - User Experience Designer"
meta_author: Terry Luke

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 718C5E #80B3FF
  primary-rgb: "217,217,217" #"128,179,255"
  secondary: 718C5E #FD6E8A
  secondary-dark: 254031 #A2122F
  background: F6F6F6

# Footer settings
footer:
  copyright: Simple Joy Yoga
  # location: Greendale
  # social: Around the Web
  # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: Facebook.com/SimpleJoyYoga
  - title: google
    url: mail-to:simplejoyyoga@gmail.com

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Credits content
credits: ''#'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
